### ISSUE TITLE
kata-agent does not use abstract Unix domain socket

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#198]
kata-agent of the latest CCv0 branch does not use  abstract Unix domain socket, when we set `KATA_AGENT_SERVER_ADDR` as follows.

```
KATA_AGENT_SERVER_ADDR=unix:///run/kata-containers/agent.sock"
```

`agent-protocol-forwarder` now needs to connect to a regular Unix domain socket, instead of a abstract Unix domain socket.

**Comment by yoheiueda** [comment]
Due to this issue, `agent-protocol-forwarder` fails with the following errors.

```
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: 2022/09/06 08:13:01 [forwarder/interceptor]
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5431e0]
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: goroutine 21 [running]:
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: bufio.(*Reader).Read(0xc000076ae0, {0xc000178120, 0xa, 0x0})
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /usr/local/go/src/bufio/bufio.go:227 +0x1a0
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: io.ReadAtLeast({0xb6eae0, 0xc000076ae0}, {0xc000178120, 0xa, 0xa}, 0xa)
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /usr/local/go/src/io/io.go:328 +0x9a
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: io.ReadFull(...)
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /usr/local/go/src/io/io.go:347
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: github.com/containerd/ttrpc.readMessageHeader({0xc000178120, 0xa, 0x0}, {0xb6eae0, 0xc000076ae0})
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /root/go/pkg/mod/github.com/containerd/ttrpc@v1.1.0/channel.go:53 +0x55
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: github.com/containerd/ttrpc.(*channel).recv(0xc000178100)
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /root/go/pkg/mod/github.com/containerd/ttrpc@v1.1.0/channel.go:101 +0x4d
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: github.com/containerd/ttrpc.(*Client).run.func2()
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /root/go/pkg/mod/github.com/containerd/ttrpc@v1.1.0/client.go:294 +0xc6
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]: created by github.com/containerd/ttrpc.(*Client).run
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 agent-protocol-forwarder[661]:         /root/go/pkg/mod/github.com/containerd/ttrpc@v1.1.0/client.go:286 +0x185
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 systemd[1]: agent-protocol-forwarder.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 06 08:13:01 k8s-worker-default-nginx-e4a2e6f1 systemd[1]: agent-protocol-forwarder.service: Failed with result 'exit-code'.
```
