### ISSUE TITLE
TestCloudServiceWithSecureComms is flaky

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#2012]
The unit test `TestCloudServiceWithSecureComms` fails in rare cases.

One example is this one.
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/10415163627/job/28845230870#step:7:188

This issue was also reported here https://github.com/confidential-containers/cloud-api-adaptor/pull/1922#issuecomment-2233863655

```
=== RUN   TestCloudServiceWithSecureComms
2024/08/16 05:32:45 [secure-comms] Using PP SecureComms: InitSshServer version v0.2
2024/08/16 05:32:45 [secure-comms] Inbound listening to port 9019
2024/08/16 05:32:45 [secure-comms] SSH service starting on port: 6001
2024/08/16 05:32:45 [secure-comms] Attestation phase: waiting for client to connect
2024/08/16 05:32:45 [secure-comms] Using PP SecureComms: InitSshClient version v0.2
2024/08/16 05:32:45 [secure-comms] CreateSecret 'sshclient'
2024/08/16 05:32:45 [secure-comms] Updating KBS with secret for: default/sshclient/publicKey
2024/08/16 05:32:45 [adaptor/cloud] failed to create PeerPodService, runtime failure may result in dangling resources NewPeerPodService: failed to get cloudProvider
2024/08/16 05:32:45 [adaptor/cloud] credential file /root/containers/auth.json is not present, skipping image auth config
2024/08/16 05:32:45 [adaptor/cloud] stored /tmp/TestCloudServiceWithSecureComms2170180551/001/123/daemon.json
2024/08/16 05:32:45 [adaptor/cloud] initdata: 
2024/08/16 05:32:45 [adaptor/cloud] create a sandbox 123 for pod mypod in namespace default (netns: )
2024/08/16 05:32:45 [adaptor/cloud] created an instance abc for sandbox 123
2024/08/16 05:32:45 [secure-comms] InitPP read/create PP secret named: pp-123
2024/08/16 05:32:46 [secure-comms] CreateSecret 'pp-123'
2024/08/16 05:32:46 [secure-comms] Updating KBS with secret for: default/pp-123/privateKey
2024/08/16 05:32:46 [secure-comms] Inbound listening to port 34959
2024/08/16 05:32:46 [secure-comms] Attestation phase: starting
2024/08/16 05:32:46 [secure-comms] Attestation phase: ssh connected - 127.0.0.1:6001
2024/08/16 05:32:46 [secure-comms] Attestation phase: client connected
2024/08/16 05:32:46 [secure-comms] Attestation phase: connected
2024/08/16 05:32:47 [secure-comms] Attestation phase: SSH server initialized keys
2024/08/16 05:32:47 [secure-comms] Attestation phase: SSH server initialized with NoClientAuth
2024/08/16 05:32:47 [secure-comms] Attestation phase: ssh skipped validating server's host key (type ssh-rsa) during attestation
2024/08/16 05:32:47 [secure-comms] Attestation phase: logged-in without key
2024/08/16 05:32:47 [secure-comms] Attestation phase: peer reported phase Attestation
2024/08/16 05:32:47 [secure-comms] Attestation phase: peer reported phase Attestation
2024/08/16 05:32:47 [secure-comms] Attestation phase: AddInbound: KBS
2024/08/16 05:32:47 [secure-comms] Attestation phase: getting keys from KBS
2024/08/16 05:32:47 [secure-comms] PpSecrets obtaining key sshclient/publicKey
2024/08/16 05:32:47 getKey client.DialContext() addr: 127.0.0.1:9019
2024/08/16 05:32:47 [secure-comms] Attestation phase: Inbound accept: KBS
2024/08/16 05:32:47 [secure-comms] Attestation phase: NewSshPeer - peer requested a tunnel channel for KBS
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy setting up for sid 123
2024/08/16 05:32:47 [secure-comms] Attestation phase: NewInboundInstance OpenChannel opening tunnel for: KBS
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/resource/default/sshclient/publicKey of host 127.0.0.1:9009
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/resource/default/sshclient/publicKey status code 200
2024/08/16 05:32:47 getKey sshclient/publicKey statusCode 200 success
2024/08/16 05:32:47 [secure-comms] PpSecrets sshclient/publicKey success
2024/08/16 05:32:47 [secure-comms] PpSecrets obtaining key pp-sid/privateKey
2024/08/16 05:32:47 getKey client.DialContext() addr: 127.0.0.1:9019
2024/08/16 05:32:47 [secure-comms] Attestation phase: Inbound accept: KBS
2024/08/16 05:32:47 [secure-comms] Attestation phase: NewSshPeer - peer requested a tunnel channel for KBS
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy setting up for sid 123
2024/08/16 05:32:47 [secure-comms] Attestation phase: NewInboundInstance OpenChannel opening tunnel for: KBS
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/resource/default/pp-123/privateKey of host 127.0.0.1:9009
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/resource/default/pp-123/privateKey status code 200
2024/08/16 05:32:47 getKey pp-sid/privateKey statusCode 200 success
2024/08/16 05:32:47 [secure-comms] PpSecrets pp-sid/privateKey success
2024/08/16 05:32:47 [secure-comms] Attestation phase: InitKubernetesPhaseSshConfig is ready
2024/08/16 05:32:47 [secure-comms] Attestation phase: peer reported it is upgrading to Kubernetes phase
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: waiting for client to connect
2024/08/16 05:32:47 [secure-comms] Attestation phase: peer done by >>> Context canceled <<<
2024/08/16 05:32:47 [secure-comms] Attestation phase: peer done by >>> chans closed <<<
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy recovered: runtime error: invalid memory address or nil pointer dereference
2024/08/16 05:32:47 [secure-comms] Outbound KBS acceptProxy recovered: runtime error: invalid memory address or nil pointer dereference
2024/08/16 05:32:47 [secure-comms] Attestation phase: done
2024/08/16 05:32:47 [adaptor/cloud] agent proxy is ready
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: starting (number of restarts 0)
2024/08/16 05:32:47 [secure-comms] Kubernetes client connected
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: ssh connected - 127.0.0.1:6001
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: connected
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: ssh host key match - ssh-rsa
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: logged-in with key SHA256:No0F5oj2VfUNG1FnLNnNStp13rj+ke3fHISiUrtU9w4
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: peer done by >>> Context canceled <<<
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: peer reported phase Kubernetes
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: NewSshPeer - peer did not ok phase verification
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: NewSshPeer - peer did not ok phase verification
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: failed: kubernetes phase: failed StartSshClient
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: peer done by >>> Phase verification failed <<<
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: peer done by >>> chans closed <<<
2024/08/16 05:32:47 [secure-comms] Retrying after Kubernetes phase failed with: failed to connect to an ssh peer
2024/08/16 05:32:47 [secure-comms] Kubernetes phase: waiting for client to connect
panic: close of closed channel

goroutine 80 [running]:
github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy.(*SshPeer).Close(0xc0003a6090, {0x2a4a102, 0xc})
	/home/runner/work/cloud-api-adaptor/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy.go:305 +0x167
github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy.NewSshPeer.func1()
	/home/runner/work/cloud-api-adaptor/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy.go:246 +0xd7a
created by github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy.NewSshPeer in goroutine 11
	/home/runner/work/cloud-api-adaptor/cloud-api-adaptor/src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy.go:217 +0x3ad
FAIL	github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/pkg/adaptor/cloud	1.546s

```

**Comment by yoheiueda** [comment]
@davidhadas do you have any idea why this happens?

**Comment by davidhadas** [comment]
Thank @yoheiueda,
I will try to reproduce and look for the source.
