### ISSUE TITLE
CAA will crash if NewServer ( server.go ) gets an error and returns nil

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#408]
I believe all the CAAs have the same problem as vsphere

govmomiClient, err := NewGovmomiClient(vmcfg)
	if err != nil {
		return nil
	}

oc logs peer-pod-controller-cca-daemon-66bh6 -n openshift-sandboxed-containers-operator
+ exec cloud-api-adaptor-vsphere vsphere -vcenter-url https://dhcp158-101.virt.lab.eng.bos.redhat.com -pause-image quay.io/bpradipt/okd-pause -template ocp-peerpods-template -data-store datastore2 -socket /run/peerpod/hypervisor.sock
2022/12/07 13:28:39 [helper/hypervisor] hypervisor config {/run/peerpod/hypervisor.sock  quay.io/bpradipt/okd-pause /run/peerpod/pods vsphere}
2022/12/07 13:28:44 [helper/hypervisor] Error from NewGovmomiClient ServerFaultCode: Cannot complete login due to an incorrect user name or password.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x505897]
goroutine 38 [running]:
github.com/confidential-containers/cloud-api-adaptor/cmd.(*starter).Start.func2()
	/home/ubuntu/remote-hyp/cloud-api-adaptor/cmd/starter.go:78 +0x77
created by github.com/confidential-containers/cloud-api-adaptor/cmd.(*starter).Start
	/home/ubuntu/remote-hyp/cloud-api-adaptor/cmd/starter.go:75 +0x1a7

**Comment by caavery** [comment]
@bpradipt
